---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart heartbeat timer
  ansible.builtin.systemd:
    name: ciris-heartbeat.timer
    state: restarted
    daemon_reload: true

- name: Enable heartbeat timer
  ansible.builtin.systemd:
    name: ciris-heartbeat.timer
    enabled: true
    state: started

- name: Enable daily checks timer
  ansible.builtin.systemd:
    name: ciris-daily-checks.timer
    enabled: true
    state: started

- name: Enable weekly security timer
  ansible.builtin.systemd:
    name: ciris-weekly-security.timer
    enabled: true
    state: started

- name: Enable weekly cleanup timer
  ansible.builtin.systemd:
    name: ciris-weekly-cleanup.timer
    enabled: true
    state: started
